name: pr_check

on:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install wasm target
        run: |
          rustup target add wasm32-unknown-unknown

      - name: Install trunk
        uses: jetli/trunk-action@68dbd78ba531c95d8ce3d262c9e63291926e9353 # v0.4.0
        with:
          version: 'latest'

      - name: Build
        run: trunk build

      - name: Run tests
        run: cargo test --verbose
